### ISSUE TITLE
Header disappears

### ISSUE THREAD

**Issue by qistoph** [DanielHabenicht/MMM-json#1]
Configuring a header as with other modules ([example](https://forum.magicmirror.builders/topic/6868/header-not-showing)), the header disappears as soon as the data is loaded.

```
{
    module: 'MMM-json',
    header: 'JSON test',
    position: 'bottom_left',
    config: {
        url: "https://jsonplaceholder.typicode.com/users", // Path to your json api
    }   
},  
```

The header is showing while data is still loading though...

**Comment by DanielHabenicht** [comment]
Ahh, thanks for the hint. This was my first module so I did not get it right the first time. 

I implemented the header inside the config, but now I changed it so that the configuration by the framework will take precedence. So it should work now. Please report back, if it is resolved.

**Comment by qistoph** [comment]
Thanks for your quick reply and fix!
