### ISSUE TITLE
Suggestion: don't strip outer arrays automatically

### ISSUE THREAD

**Issue by qistoph** [DanielHabenicht/MMM-json#4]
https://github.com/DanielHabenicht/MMM-json/blob/d63c154ac2d074e80ab34da331b9ca05a149f53c/node_helper.js#L28-L31

If the outer object is an array it is stripped here. Though I would think it's quite elegant if MMM-json would just display arrays as arrays.

Especially considering my PR #2, how nice and powerful would it be if jq would produce an array and it would be displayed.

**An example**
My request + jq generate a list of episodes to watch:
`[.result.episodes[]|[.showtitle,.title]|join(" - ")]`

```
[
  "Sherlock - The Sign of Three",
  "Suits - She's Gone",
  "The Boys - The Name of the Game",
]
```

Currently it would display the first string, but split into characters:
![image](https://user-images.githubusercontent.com/678500/107003582-53dd6500-678d-11eb-9cf5-27b1d0df4b39.png)

A work around is to include an additional array
`[[.result.episodes[]|[.showtitle,.title]|join(" - ")]]`

![image](https://user-images.githubusercontent.com/678500/107003826-b0408480-678d-11eb-99b6-07eeaf9af98f.png)

It would imho be even nicer if MMM-json would display arrays just as lists, without the indexes (0, 1, 2) in my example. Maybe even allow single values to be displayed?

If you're interested a a PR, please let me know.

**Comment by DanielHabenicht** [comment]
Mhm, that would be reasonable I think. It was just that my first use case was an array of objects so I coded it into the application instead of my configuration. ^^ 

I think I will setup versioning before your PR gets merged but you can incorporate it into your current one if you like.
