### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by nirvine** [DanielHabenicht/MMM-json#6]
I am using this module to get indoors temperature and humidity from a Sensibo air conditioning smart control. the json response from the device is in the format
{"status": "success", "result": [{"temperature": 17.2, "humidity": 67.1, "time": {"time": "2021-08-28T09:49:56.501677Z", "secondsAgo": 19}}]}

My config is:
 values: [
      {
        title: "Temperature",
        query: "$.result[:0].temperature"
      },
      {
        title: "Humidity",
       query: "$.result[1)].humidity",
      }
    ]

This works at the jsonpath evaluator, and get the correct responses. 
But on the MM it only shows "loading". 
If I just use empty brackets for the values, I do get "Status" and "Result" showing on the MM. 
What have I done wrong?
I can send you the URL if that helps to resolve the problem.

**Comment by DanielHabenicht** [comment]
Hi, sorry for the late reply. 

Are there any errors in the MagicMirror Server or the Webbrowser?
If you have a public URL I am happy to give it a try.

**Comment by nirvine** [comment]
I changed over to use MMM-JsonTable, and found that one worked.
